# Uncomment the next line to define a global platform for your project
# platform :ios, '14.2'

target 'SignalRPushnotification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftSignalRClient'
  # Pods for SignalRPushnotification

  # Pods for FirebaseStarterKit
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/AdMob'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
end
